export const pokemons = [
  {
    id: 'UG9rZWivbjowMDE=',
    number: '001',
    name: 'Bulbasaur',
    classification: 'Seed Pokémon',
    fleeRate: 0.1,
    image: 'https://img.pokemondb.net/artwork/bulbasaur.jpg',
  },
  {
    id: 'UG9rZW1vbjowMDI',
    number: '002',
    name: 'Ivysaur',
    classification: 'Lizard Pokémon',
    fleeRate: 0.07,
    image: 'https://img.pokemondb.net/artwork/ivysaur.jpg',
  },
  {
    id: 'UG9rZWivbjowMD',
    number: '001',
    name: 'Bulbasaur',
    classification: 'Seed Pokémon',
    fleeRate: 0.1,
    image: 'https://img.pokemondb.net/artwork/bulbasaur.jpg',
  },
  {
    id: 'UG9rZW1vbjowM',
    number: '002',
    name: 'Ivysaur',
    classification: 'Lizard Pokémon',
    fleeRate: 0.07,
    image: 'https://img.pokemondb.net/artwork/ivysaur.jpg',
  },
  {
    id: 'UG9rZWivbjow',
    number: '001',
    name: 'Bulbasaur',
    classification: 'Seed Pokémon',
    fleeRate: 0.1,
    image: 'https://img.pokemondb.net/artwork/bulbasaur.jpg',
  },
  {
    id: 'UG9rZW1vbjo',
    number: '002',
    name: 'Ivysaur',
    classification: 'Lizard Pokémon',
    fleeRate: 0.07,
    image: 'https://img.pokemondb.net/artwork/ivysaur.jpg',
  },
  {
    id: 'UG9rZWivbj',
    number: '001',
    name: 'Bulbasaur',
    classification: 'Seed Pokémon',
    fleeRate: 0.1,
    image: 'https://img.pokemondb.net/artwork/bulbasaur.jpg',
  },
  {
    id: 'UG9rZW1vb',
    number: '002',
    name: 'Ivysaur',
    classification: 'Lizard Pokémon',
    fleeRate: 0.07,
    image: 'https://img.pokemondb.net/artwork/ivysaur.jpg',
  },
  {
    id: 'UG9rZWiv',
    number: '001',
    name: 'Bulbasaur',
    classification: 'Seed Pokémon',
    fleeRate: 0.1,
    image: 'https://img.pokemondb.net/artwork/bulbasaur.jpg',
  },
];
